spring.application.name=exo-form-backend
spring.datasource.url=jdbc:mysql://localhost:3306/demo-crud?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET:L3JQgfzLhKKSEtLBD7+UKqsmfPcJ4yoCAICFb25fyYU=}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION:900000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:604800000}

